set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.

" different version somewhere else.
Plugin 'ascenator/L9', {'name': 'newL9'}
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'mtscout6/syntastic-local-eslint.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'tpope/vim-fugitive'
Plugin 'valloric/youcompleteme'
Plugin 'morhetz/gruvbox'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'kien/ctrlp.vim'
Plugin 'mkitt/tabline.vim'
Plugin 'tpope/vim-surround'
Plugin 't9md/vim-choosewin'
Plugin 'marijnh/tern_for_vim'
"Plugin 'yggdroot/indentline'
Plugin 'nathanaelkane/vim-indent-guides'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
       " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal       
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" my own attemp to install plugins in vim

let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_ngdoc = 1
let g:javascript_plugin_flow = 1
set foldmethod=syntax
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
"the following is for enabling esilnt for syntastic
let g:syntastic_javascript_checkers = ['eslint']

inoremap jk <esc>
nnoremap <s-j> 12j
nnoremap <s-k> 12k
nnoremap <d-j> 5j
nnoremap <d-k> 5k

nnoremap <s-y> :NERDTree<CR>
if has ('gui_running')
	set guifont=Sauce\ Code\ Powerline\ Light:h15
endif

syntax enable
"colorscheme molokai 
colorscheme gruvbox
set background=dark    " Setting dark mode with gruvox
let g:gruvbox_bold = 0
"let g:molokai_original = 1
"let g:rehash256 = 1

set tabstop=2
set shiftwidth=2
set expandtab
set cursorline
set number
 
"let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:bubblegum = 1
let g:sol = 1
let g:airline_theme='light'

"ignore case when pattern searching, but capital letters will
"be capital matched
:set ignorecase
:set smartcase 
:set nolz

let g:ycm_seed_identifiers_with_syntax = 1
let g:ctrlp_map = '<D-p>'
let g:ctrlp_working_path_mode = 0
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$|node_modules'


"window navagation, resizing related
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <D-left> :vertical resize -10<cr>
nnoremap <D-down> :resize +10<cr>
nnoremap <D-up> :resize -10<cr>
nnoremap <D-right> :vertical resize +10<cr>

:set directory=~/.vimSwapFiles//

"choose-win:
let g:choosewin_overlay_enable = 0
"nmap  <s-h> <Plug>(choosewin)
nmap ff <Plug>(choosewin)

"NERTree:
let NERDTreeQuitOnOpen=1

"indent:
set smartindent
set autoindent
"indent guide:
"let g:indentLine_color_term = 239
let g:indent_guides_auto_colors = 1
let g:indent_guides_start_level = 1
let g:indent_guides_guide_size = 1
":IndentGuidesEnable
